version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-admin:
    build:
      dockerfile: ./kafka-admin/Dockerfile
    image: kafka-admin
    depends_on:
      - kafka
    ports:
      - 9099:8099
    container_name: kafka-admin

  kafka-producer:
    build:
      dockerfile: ./kafka-producer/Dockerfile
    image: kafka-producer
    depends_on:
      - kafka-admin
    ports:
      - 9090:8090
    container_name: kafka-producer
  kafka-consumer:
    build:
      dockerfile: ./kafka-consumer/Dockerfile
    image: kafka-consumer
    ports:
      - 9091:8091
    container_name: kafka-consumer

