version: "3.4"

services:
  kafka-broker:
    build:
      dockerfile: ./kafka-broker/Dockerfile
    image: kafka-broker
    ports:
      - 9099:8099
    container_name: kafka-broker
  kafka-producer:
    build:
      dockerfile: ./kafka-producer/Dockerfile
    image: kafka-producer
    ports:
      - 9090:8090
    container_name: kafka-producer
  kafka-consumer:
    build:
      dockerfile: ./kafka-consumer/Dockerfile
    image: kafka-consumer
    ports:
      - 9091:8091
    container_name: kafka-consumer

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
