version: '3.8'

services:
  kafka-admin:
    container_name: kafka-admin
    image: kafka-admin
    build:
      dockerfile: ./kafka-admin/Dockerfile
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
    ports:
      - 8081:8081
    networks:
      - kafka_network

  kafka-producer:
    container_name: kafka-producer
    image: kafka-producer
    build:
      dockerfile: ./kafka-producer/Dockerfile
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-admin
    ports:
      - 8082:8082
    networks:
      - kafka_network

  kafka-consumer:
    container_name: kafka-consumer
    image: kafka-consumer
    build:
      dockerfile: ./kafka-consumer/Dockerfile
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-admin
      - kafka-producer
    ports:
      - 8083:8083
    networks:
      - kafka_network

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - kafka_network

  kafka-1:
    container_name: kafka-1
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    networks:
      - kafka_network

  kafka-2:
    container_name: kafka-2
    image: wurstmeister/kafka:latest
    ports:
      - 9093:9093
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    networks:
      - kafka_network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    ports:
      - 9999:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - zookeeper
      - kafka-1
      - kafka-2
    networks:
      - kafka_network

networks:
  kafka_network:
    name: kafka_network_demo