server:
  port: 8099

spring:
  kafka:
    bootstrap-servers: kafka-1:29092,kafka-2:39092
  #bootstrap-servers: localhost:29092,localhost:39092

topic:
  default-topic-name: chuck-norris-topic
  messages-per-request: 10
