server:
  port: 8099

spring:
  kafka:
    bootstrap-servers: kafka-demo-kafka-1-1:29092,kafka-demo-kafka-1-1:39092
  #bootstrap-servers: localhost:29092,localhost:39092
  #kafka-1:29092
topic:
  default-topic-name: chuck-norris-topic
  messages-per-request: 10
